services:
  langgraph-agent:
    container_name: langgraph-agent
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - graph_agent.env
    ports:
      - "8000:8000"

  # Choose one of the following VOICEVOX Engine configurations based on your environment (GPU usage is recommended if possible)
  # For CPU-only usage
  voicevox_engine:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "50021:50021"
    tty: true

  # For Nvidia GPU usage
  # voicevox_engine:
  #   image: voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
  #   ports:
  #     - "50021:50021"
  #   tty: true
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
