services:
  chainlit-dev:
    container_name: chainlit-dev
    image: "mcr.microsoft.com/devcontainers/python:3.12-bookworm"
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: vscode
    tty: true
    env_file:
      - ../graph_agent.env
    volumes:
      - ../:/workspace:cached

  # Launch one of the following VOICEVOX Engine options depending on your environment (GPU usage is recommended if possible)
  # When using CPU only
  voicevox_engine-dev:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "50021:50021"
    tty: true

  # When using Nvidia GPU
  # voicevox_engine-dev:
  #   image: voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
  #   ports:
  #     - "50021:50021"
  #   tty: true
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
